import "./globals.css";
import { Inter } from "next/font/google";
import { Noto_Sans_JP } from "@next/font/google";

import "bootstrap/dist/css/bootstrap.min.css";
// import { AuthProvider } from "@/lib/firebase/Auth/AuthContext";

const notoSansJP600 = Noto_Sans_JP({
  weight: "600",
  display: "swap",
  preload: false,
});
const notoSansJP500 = Noto_Sans_JP({
  weight: "500",
  display: "swap",
  preload: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head></head>
      <body className={notoSansJP600.className}>
        {/* <AuthProvider> */}
        {children}
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
